# Dependencies
markdown:         redcarpet
highlighter:      rb-pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Competitive Cyber Clubs'
tagline:          'Website for Competitive Cyber Clubs'
description:      'Website for the Competitive Cyber Clubs Discord'
url:              http://competitivecyberclubs.org/
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.1

github:
  repo:           https://github.com/competitivecyberclubs/competitivecyberclubs.github.io
